Content:
    Articuno:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: Articuno
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
    MooseDocs.extensions.sqa:
        active: true
        categories:
            articuno: !include ${ROOT_DIR}/doc/sqa_articuno.yml
            framework: !include ${MOOSE_DIR}/framework/doc/sqa_framework.yml
        reports: !include ${ROOT_DIR}/doc/sqa_reports.yml
    MooseDocs.extensions.template:
        active: true
